version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=llama2
      - TWITCH_CATEGORY=Just Chatting
      - TWITCH_CHANNEL=${TWITCH_CHANNEL}
      - TWITCH_OAUTH_TOKEN=${TWITCH_OAUTH_TOKEN}
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - WHISPER_MODEL=base
      - USE_CUDA=false
      - WHISPER_BEAM_SIZE=1
      - WHISPER_BEST_OF=1
      - WHISPER_TEMPERATURE=0.0
      - WHISPER_CONDITION_PREVIOUS=false
      - WHISPER_MIN_CONFIDENCE=0.5
    depends_on:
      - ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ollama_data:
    name: stream_npc_ollama_data 